//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTon
    {
        public BaoCaoTon()
        {
            this.BaoCaoTon_CT = new HashSet<BaoCaoTon_CT>();
        }
    
        public string MaBaoCao { get; set; }
        public Nullable<System.DateTime> ThangBaoCao { get; set; }
        public string NhanVien { get; set; }
    
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<BaoCaoTon_CT> BaoCaoTon_CT { get; set; }
    }
}
