//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoNo
    {
        public BaoCaoNo()
        {
            this.BaoCaoNo_CT = new HashSet<BaoCaoNo_CT>();
        }
    
        public string MaBaoCao { get; set; }
        public Nullable<System.DateTime> ThangBaoCao { get; set; }
        public string NhanVien { get; set; }
    
        public virtual ICollection<BaoCaoNo_CT> BaoCaoNo_CT { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
