//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGia
    {
        public BaoGia()
        {
            this.BaoGia_CT = new HashSet<BaoGia_CT>();
        }
    
        public string MaBaoGia { get; set; }
        public string NhanVien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
    
        public virtual ICollection<BaoGia_CT> BaoGia_CT { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
