//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public DonDatHang()
        {
            this.DonDatHang_CT = new HashSet<DonDatHang_CT>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaDonHang { get; set; }
        public string KhachHang { get; set; }
        public string NhanVien { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual ICollection<DonDatHang_CT> DonDatHang_CT { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
