//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.BaoCaoNo_CT = new HashSet<BaoCaoNo_CT>();
            this.DonDatHangs = new HashSet<DonDatHang>();
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuThuTiens = new HashSet<PhieuThuTien>();
            this.PhieuXuats = new HashSet<PhieuXuat>();
        }
    
        public string MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> SoNo { get; set; }
    
        public virtual ICollection<BaoCaoNo_CT> BaoCaoNo_CT { get; set; }
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<PhieuThuTien> PhieuThuTiens { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
    }
}
