//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgonNgu
    {
        public NgonNgu()
        {
            this.NhanNgonNgus = new HashSet<NhanNgonNgu>();
        }
    
        public int MaNgonNgu { get; set; }
        public string KyHieu { get; set; }
        public string TenNgonNgu { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<NhanNgonNgu> NhanNgonNgus { get; set; }
    }
}
