//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuTien
    {
        public string MaPhieuThu { get; set; }
        public string KhachHang { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public string NhanVien { get; set; }
        public Nullable<decimal> SoTienThu { get; set; }
    
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
