//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.PhieuXuat_CT = new HashSet<PhieuXuat_CT>();
        }
    
        public string MaPhieuXuat { get; set; }
        public string NhanVien { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string KhachHang { get; set; }
        public string DiaChiNhan { get; set; }
        public string HoaDon { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual HoaDon HoaDon1 { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<PhieuXuat_CT> PhieuXuat_CT { get; set; }
    }
}
