//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.PhieuNhap_CT = new HashSet<PhieuNhap_CT>();
        }
    
        public string MaPhieuNhap { get; set; }
        public string NhanVien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<PhieuNhap_CT> PhieuNhap_CT { get; set; }
    }
}
