//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat_CT
    {
        public string MaPhieuXuat { get; set; }
        public string MaSanPham { get; set; }
        public int SoLuongYeuCau { get; set; }
        public int SoLuongThucXuat { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
