//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BaoCaoTon_CT = new HashSet<BaoCaoTon_CT>();
            this.BaoGia_CT = new HashSet<BaoGia_CT>();
            this.DonDatHang_CT = new HashSet<DonDatHang_CT>();
            this.HoaDon_CT = new HashSet<HoaDon_CT>();
            this.PhieuNhap_CT = new HashSet<PhieuNhap_CT>();
            this.PhieuXuat_CT = new HashSet<PhieuXuat_CT>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<int> DonVi { get; set; }
        public Nullable<int> NhomSanPham { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual ICollection<BaoCaoTon_CT> BaoCaoTon_CT { get; set; }
        public virtual ICollection<BaoGia_CT> BaoGia_CT { get; set; }
        public virtual ICollection<DonDatHang_CT> DonDatHang_CT { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual ICollection<HoaDon_CT> HoaDon_CT { get; set; }
        public virtual NhomSanPham NhomSanPham1 { get; set; }
        public virtual ICollection<PhieuNhap_CT> PhieuNhap_CT { get; set; }
        public virtual ICollection<PhieuXuat_CT> PhieuXuat_CT { get; set; }
    }
}
